:log info "Export beginning now";
:global  varDate ([/system clock get date]) ;
:global  varMonth [:pick $varDate 0 3];
:global  varDay [:pick $varDate 4 6];
:global  varYear [:pick $varDate 7 11];
:global backupfile ([$varMonth]."-".[$varDay]."-".[$varYear]."-export.rsc") ;
/export file=$backupfile;
:log info "export pausing for 20s";
:delay 20s;
:file remove $yesterday_3;
:global yesterday_3 ([:put $yesterday_2]);
:global yesterday_2 ([:put $yesterday_1]);
:global yesterday_1 ([:put $backupfile]);
:log info "export being emailed";
/tool e-mail send to="monitor@test.com" subject="RouterOS configuration export" body="RouterOS configuration export file" file=$backupfile;
:log info "export del file pausing for 120s";
:delay 120s;
:log info "export finished";
